frontend:
  themes: !include_dir_merge_named themes

lovelace:
  dashboards:
    jarvis-command-center:
      mode: yaml
      filename: jarvis-dashboard.yaml
      title: Jarvis
      icon: mdi:circle-double
      show_in_sidebar: true
      require_admin: false
    jarvis-component-catalog:
      mode: yaml
      filename: jarvis-component-catalog.yaml
      title: Jarvis UI Catalog
      icon: mdi:view-dashboard-edit-outline
      show_in_sidebar: false
      require_admin: false
