"""Provider-neutral storage contract for curated Jarvis knowledge."""

from __future__ import annotations

from typing import Protocol

from jarvis.models.knowledge import KnowledgeRecord


class DuplicateKnowledgeError(Exception): pass
class KnowledgeNotFoundError(Exception): pass
class InvalidKnowledgeOperationError(Exception): pass


class KnowledgeStore(Protocol):
    def create(self, record: KnowledgeRecord) -> KnowledgeRecord: ...
    def get(self, knowledge_id: str) -> KnowledgeRecord: ...
    def list_records(self) -> tuple[KnowledgeRecord, ...]: ...
    def update(self, record: KnowledgeRecord) -> KnowledgeRecord: ...
    def delete(self, knowledge_id: str) -> None: ...
    def clear(self) -> None: ...
    def exists(self, knowledge_id: str) -> bool: ...
